Задача 1. Робота з зображеннями як з матрицями

Умова

Цифрові зображення у комп'ютері зберігаються як масиви чисел (матриці). Будь-яке чорно-біле зображення для комп'ютера — це просто матриця чисел, де кожне число — яскравість пікселя від 0 до 255. Редагування зображень базується на арифметичних операціях з цими матрицями.



Ви працюєте з фрагментом зображення розміром
3
×
3
3×3 пікселі.



Дано матрицю зображення M та матрицю накладеного ефекту .


M=
​
  
100
50
0
​
  
150
100
50
​
  
200
150
100
​
  
​

E=
​
  
20
10
5
​
  
30
20
10
​
  
40
30
15
​
  
​




Необхідно реалізувати три алгоритми обробки:

Зміна контрасту. Необхідно зменшити яскравість зображення
M
M. Це множення матриці на скаляр (число)
λ
λ. Кожен елемент матриці множиться на це число 0.5
Корекція яскравості. Це додавання скаляра
c
c до матриці
M
M. Число додається до кожного елемента матриці. Додайте до зображення
M
M число 25. Це збільшить яскравість кожного пікселя на 25.
Змішування (Blending). Ми створюємо нове зображення, змішуючи оригінал та ефект у певній пропорції. Для цього створи нове зображення як лінійну комбінацію:

0.8⋅M+0.2⋅E. Це імітує прозорість ефекту.


Завдання:

Обчисліть це аналітично та покажіть проміжні кроки.
Використовуючи бібліотеку numpy, напишіть програму, що виконує ті самі операції та перевіряє твої аналітичні обчислення. Виведіть на екран результати обчислень для кожного фільтра.


In [4]:
import numpy as np

# Матриця зображення M
M = np.array([[100, 150, 200],
              [50, 100, 150],
              [0, 50, 100]])

# Матриця ефекту E
E = np.array([[20, 30, 40],
              [10, 20, 30],
              [5, 10, 15]])

# Параметри
lambda_value = 0.5   # коефіцієнт контрасту
c_value = 25         # корекція яскравості
alpha = 0.8          # вага оригіналу
beta = 0.2           # вага ефекту

# 1. Зміна контрасту
contrast_M = lambda_value * M
print("Зміна контрасту:\n", contrast_M)

# 2. Корекція яскравості
brightness_M = M + c_value
print("\nКорекція яскравості:\n", brightness_M)

# 3. Змішування
blend_M = alpha * M + beta * E
print("\nЗмішування:\n", blend_M)


Зміна контрасту:
 [[ 50.  75. 100.]
 [ 25.  50.  75.]
 [  0.  25.  50.]]

Корекція яскравості:
 [[125 175 225]
 [ 75 125 175]
 [ 25  75 125]]

Змішування:
 [[ 84. 126. 168.]
 [ 42.  84. 126.]
 [  1.  42.  83.]]


Задача 2. Пошук схожих фільмів

Рекомендаційні системи як Netflix або YouTube часто представляють користувачів та контент у вигляді векторів.

Є профіль користувача — це вектор інтересів до жанрів [Екшн, Комедія, Драма].



Також є три фільми
A
,
B
,
C
A,B,C, кожен з яких має таку ж структуру характеристик.

Вектор профілю користувача:


u=(8,2,5)



Та три фільмів.

Фільм A (Action Movie):
v
A
​
 =(9,1,2)

Фільм B (Comedy Movie):

v
B
​
 =(1,9,8)

Фільм C (Drama Movie):

v
C
​
 =(7,2,6)

Ваша задача — знайти фільм, який найбільше підходить користувачу, порівнявши вектори їхніх характеристик.



📐Нагадуємо, чим менший кут між цими векторами у багатовимірному просторі, тим більше схожі об'єкти. Мірою цієї схожості є косинусна подібність. Вона показує, наскільки вектори "дивляться" в один бік. Значення коливається від -1 (протилежні) до 1 (ідентичні).

Формула косинусної подібності:

cosθ=
∥u∥⋅∥v∥
u⋅v
​
 ,

де
u
⋅
v
u⋅v — скалярний добуток, а
∥
u
∥
,
∥
v
∥
∥u∥,∥v∥ — довжина (норма) вектора.



Аналітична частина розв'язку.

Обчисліть аналітично норму вектора користувача
∥
u
∥
∥u∥.
Обчисліть схожість (similarity score) профілю користувача з кожним із трьох фільмів.
Порівняйте отримані значення та визначте, який фільм має найвищий бал схожості.


Програмна частина розв'язку.

Використовуючи бібліотеку numpy напишіть програму та виконайте наступні кроки:

Створіть вектор профілю користувача та вектори фільмів
Реалізуйте функцію косинусної схожості за формулою
Обчисліть схожість для кожного фільму
Виведіть на екран коефіцієнти схожості для кожного фільму та назву фільму, вектор якого має найбільше значення косинусної подібності.
Перевірте себе та порівняйте з аналітичними обчисленнями, щоб вони збігалися

In [5]:
import numpy as np

# Вектор користувача
u = np.array([8, 2, 5])

# Вектори фільмів
vA = np.array([9, 1, 2])
vB = np.array([1, 9, 8])
vC = np.array([7, 2, 6])

# Функція косинусної подібності
def cosine_similarity(u, v):
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

# Обчислення схожості
sim_A = cosine_similarity(u, vA)
sim_B = cosine_similarity(u, vB)
sim_C = cosine_similarity(u, vC)

print("Фільм A:", sim_A)
print("Фільм B:", sim_B)
print("Фільм C:", sim_C)

# Найкращий фільм
similarities = {"A": sim_A, "B": sim_B, "C": sim_C}
best_movie = max(similarities, key=similarities.get)
print("Найбільш схожий фільм:", best_movie)

Фільм A: 0.9392659661346112
Фільм B: 0.5664036369783693
Фільм C: 0.9892499382749278
Найбільш схожий фільм: C


Задача 3. Аналіз виробництва

Ви керуєте цехом зі збірки FPV-дронів.

У вас три моделі: "Розвідник"
x
1
x
1
​
 , "Камікадзе"
x
2
x
2
​
  та важкий "Вантажний" дрон
x
3
x
3
​
 .



Кожен із них потребує різного набору комплектуючих: моторів, польотних контролерів та акумуляторів.



В кінці зміни приходить звіт про загальні витрати деталей, але через збій у системі ти втратив дані про те, скільки саме дронів кожного типу було зібрано.



Це класична задача на відновлення даних, яка вирішується через систему лінійних рівнянь

Ax=b.



Відомі витрати на один дрон, це матриця
A
A, де стовпці — це типи дронів:

"Розвідник": 4 мотори, 1 контролер, 1 акумулятор.
"Камікадзе": 4 мотори, 1 контролер, 2 акумулятори.
"Вантажний": 6 моторів, 2 контролери, 4 акумулятори.


Всього за зміну було витрачено вектор
b
b:

460 моторів
130 контролерів
240 акумуляторів


Використовуючи бібліотеку numpy, напишіть програму та виконайте наступні кроки:

Сформуйте матрицю коефіцієнтів
A
A та вектор вільних членів
b
b.
Перед розв'язанням перевірте, чи має система єдиний розв'язок. Для цього обчисліть визначник матриці
A
A за допомогою функції np.linalg.det(A). Якщо він не дорівнює нулю — розв'язок існує.
Розв'яжіть систему за допомогою np.linalg.solve(A, b) і знайдіть вектор
x
x. Це буде кількість зібраних дронів кожного типу.
Виконайте перевірку правильності розрахунків: перемножте матрицю
A
A на знайдений вектор
x
x. Результат має збагатися з вектором
b
b.
Виведіть кількість дронів кожного типу та результати перевірки.


In [6]:
import numpy as np

# Матриця витрат A
A = np.array([[4, 4, 6],
              [1, 1, 2],
              [1, 2, 4]])

# Вектор витрат b
b = np.array([460, 130, 240])

# Визначник
det_A = np.linalg.det(A)
print("Визначник матриці A:", det_A)

if det_A != 0:
    # Розв’язок системи
    x = np.linalg.solve(A, b)
    print("Кількість дронів (Розвідник, Камікадзе, Вантажний):", x)

    # Перевірка
    check = A @ x
    print("Перевірка A*x:", check)
else:
    print("Система не має єдиного розв’язку.")


Визначник матриці A: -2.0
Кількість дронів (Розвідник, Камікадзе, Вантажний): [20. 50. 30.]
Перевірка A*x: [460. 130. 240.]


Задача 4. Прогноз тренду

При моніторингу IT-інфраструктури дані часто надходять із шумом.

Навантаження на CPU сервера може коливатися, але загальний тренд вказує на поступове зростання.

Щоб передбачити, коли сервер досягне критичного навантаження, потрібно побудувати лінію тренду

y=kx+b.



Оскільки точки не лежать ідеально на одній прямій, точного розв'язку системи не існує, тому використовується метод найменших квадратів (МНК).



Дано виміри завантаження CPU y протягом 5 годин t.

Час t=[1,2,3,4,5]

Навантаження y=[22,28,37,45,53]


Використовуючи бібліотеку numpy, напишіть програму та виконайте наступні кроки:

Сформуйте матрицю A. Пам'ятайте, що для знаходження вільного члена b матриця повинна містити стовпчик зі значень t та стовпчик з одиниць.

Знайдіть коефіцієнти прямої k та b за допомогою функції np.linalg.lstsq(A, y). Ця функція повертає найкращий наближений розв'язок.
Використовуючи знайдені коефіцієнти, обчисліть прогнозоване навантаження на 6-ту годину за формулою  
у =k⋅6+b.
Виведіть рівняння отриманого тренду та прогноз.

Опціональне завдання з зірочкою (+5 бонусних балів). Функція np.linalg.lstsq() використовує нормальне рівняння для знаходження оптимальних коефіцієнтів. Реалізуйте цей метод вручну.



Знайдіть коефіцієнти k - нахил, та b - зсув через нормальне рівняння  Ax=ATy. Де
x=[k,b]
T
  — вектор невідомих коефіцієнтів.



Кроки:

Обчислити ATA

Обчислити AT y
Розв'яжіть систему через np.linalg.solve()
Порівняйте результат з lstsq — вони мають збігатися

In [7]:
import numpy as np

# Дані
t = np.array([1, 2, 3, 4, 5])
y = np.array([22, 28, 37, 45, 53])

# Матриця A (стовпчик t + стовпчик одиниць)
A = np.column_stack((t, np.ones(len(t))))

# Розв’язок через lstsq
coeffs, residuals, rank, s = np.linalg.lstsq(A, y, rcond=None)
k, b = coeffs
print("Рівняння тренду (через lstsq): y = {:.2f}x + {:.2f}".format(k, b))

# Прогноз на 6-ту годину
y_pred = k * 6 + b
print("Прогноз на 6-ту годину:", y_pred)

# Опціонально: нормальне рівняння
ATA = A.T @ A
ATy = A.T @ y
coeffs_normal = np.linalg.solve(ATA, ATy)
k_normal, b_normal = coeffs_normal
print("Рівняння тренду (нормальне рівняння): y = {:.2f}x + {:.2f}".format(k_normal, b_normal))

Рівняння тренду (через lstsq): y = 7.90x + 13.30
Прогноз на 6-ту годину: 60.7
Рівняння тренду (нормальне рівняння): y = 7.90x + 13.30
